apiVersion: v1
kind: Service
metadata:
  name: essay-app-service
  labels:
    app: essay-app
spec:
  selector:
    app: essay-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
